name: "Deploy"
description: "Deploy backend"

inputs:
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  slack-webhook-url:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      id: checkout
    - name: Deploy Backend
      id: deploy
      run: echo "Deploy OK"
      shell: bash
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        slack-webhook-url: ${{ inputs.slack-webhook-url }}
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      if: github.ref_name == 'master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      if: github.ref_name == 'master'
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
