name: "Check conventional compliance on PR"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  check-compliance:
    name: "Check compliance"
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: "Checkout"
        if: ${{ github.event.action != 'edited' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "Misc: Check commit messages"
        if: ${{ github.event.action != 'edited' }}
        uses: aevea/commitsar@v0.20.1
        with:
          cache: 'docker'

      - name: "Misc: Check PR title"
        if: always()
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
