name: "Check conventional compliance on PR"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-compliance:
    name: "Check conventional compliance"
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Misc: Check commit messages for conventional compliance"
        uses: aevea/commitsar@v0.20.1

      - name: "Misc: Check PR title for conventional compliance"
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
