name: "Create version tag on push to master"

on:
  push:
    branches:
      - master

jobs:
  create_tag:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    outputs:
      GIT_TAG: ${{ steps.tag.outputs.new_tag }}

    steps:
      - name: "Misc: Analytics with gitboard.io"
        uses: gitboard-io/gitboard-action@main
        with:
          username: hos-dimabutyrin
          key: ${{ secrets.GITBOARD_SECRET }}

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Misc: Bump version and push tag"
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  create_release:
    needs: create_tag
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: write
    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.create_tag.outputs.GIT_TAG }}
          generateReleaseNotes: true
