name: "Manual Deploy Backend"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  deploy_backend_staging:
    uses: ./.github/workflows/deploy-backend.yml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GITBOARD_SECRET: ${{ secrets.GITBOARD_SECRET }}
