name: "Deploy Backend"

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCOUNT:
        required: true
      AWS_REGION:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      GITBOARD_SECRET:
        required: true
    inputs:
      environment:
        type: string
        required: true

concurrency:
  group: deploy-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    # using: "composite"
    steps:
      - name: "Misc: Analytics with gitboard.io"
        uses: gitboard-io/gitboard-action@main
        with:
          username: hos-dimabutyrin
          key: ${{ secrets.GITBOARD_SECRET }}
      - name: Debug
        run: echo $GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      - uses: actions/checkout@v2
        id: checkout
      - name: Deploy Backend
        id: deploy
        run: |
          sleep 30
          echo "Deploy OK on ${{ inputs.environment }}"
          echo "Git $(git status)"
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: Slack Notification
        if: |
          ( failure() && inputs.environment == 'prod') ||
          ( failure() && inputs.environment == 'staging')
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#debugandtest'
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
