name: Main Workflow

on:
  # Decorate a PR
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - staging
      - master
  # Update info for master and staging branches
  push:
    branches:
      - staging
      - master

jobs:
  test:
    name: "Run Main Workflow"
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: "Misc: Analytics with gitboard.io"
        uses: gitboard-io/gitboard-action@main
        with:
          username: hos-dimabutyrin
          key: ${{ secrets.GITBOARD_SECRET }}

      - name: Debug
        run: echo $GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}

      - uses: actions/checkout@v2
      - name: Run tests
        run: |
            echo "OK"

  check-if-pr-is-ready:
    name: Check if this a Draft PR
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: "Misc: Analytics with gitboard.io"
        uses: gitboard-io/gitboard-action@main
        with:
          username: hos-dimabutyrin
          key: ${{ secrets.GITBOARD_SECRET }}
      - name: Check if it is a draft PR
        run: |
            echo "Looks like it is not a draft PR. Continue..."
  test2:
    name: "Run Main Workflow 2"
    needs: check-if-pr-is-ready
    runs-on: ubuntu-latest
    steps:
      - name: "Misc: Analytics with gitboard.io"
        uses: gitboard-io/gitboard-action@main
        with:
          username: hos-dimabutyrin
          key: ${{ secrets.GITBOARD_SECRET }}

      - uses: actions/checkout@v2

      - name: Run tests
        run: |
            echo "OK"
