name: "Merge staging to dev"

on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge staging to dev
      run: |
          git fetch --unshallow
          git checkout dev
          git pull
          git merge --no-ff staging -m "Auto-merge staging to dev"
          git push
