name: "Test on PR"

on:
  pull_request:
    branches:
      - dev
      - staging
      - master
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge target branch into PR branch
        uses: ./.github/actions/merge-target-branch

      - name: Install SonarQube Tools
        shell: bash
        run: |
          sudo gem install slather

      - name: Get Code Coverage
        shell: bash
        run: |
          echo slather coverage --sonarqube-xml ${params} ${project}
          bash -c "slather coverage --sonarqube-xml ${params} ${project}"
        env:
          project: '"Challenge App.xcodeproj"'
          params: '
          --scheme "Challenge App - Development"
          --workspace "Challenge App.xcworkspace"'

      - name: Run tests
        run: |
            echo "Run test"
            ls -lah .github/**/**

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: '@Dima Butyrin'
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON_EMOJI: ':github_octocat:'
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
