name: "Test on PR"

on:
  pull_request:
    branches:
      - dev
      - staging
      - master
      - main

jobs:
  run_tests:
    uses: ./.github/workflows/slack.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
