name: "Test on PR"

on:
  pull_request:
    paths:
      - '**/**'
    branches:
      - dev
      - staging
      - master
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/merge-target-branch
      - name: Run tests
        run: |
            echo "Run test"
            ls -lah .github/**/**